#!/bin/bash
# Flush all existing rules
iptables -F

#Allow root running applications send data out
iptables -A OUTPUT -m owner --uid-owner root -j ACCEPT
iptables -A OUTPUT -m owner --gid-owner root -j ACCEPT
#Block all other OUTPUT on eth0
iptables -A OUTPUT -o eth0 -j DROP

#Block incoming SSH over IPOP and Eth0
iptables -A INPUT -p tcp -i tap0 --dport 22 -j DROP
iptables -A INPUT -p tcp -i eth0 --dport 22 -j DROP

if test -f /home/griduser/local_iprules; then
  /home/griduser/local_iprules
fi
