#!/bin/bash
# This script does the following:
# (a) Flushes the existing iptables rules and 
# (b) Defines the iptables rules for Grid-Appliance.
# (c) Displays the current iptable

# The rules and other functionalities provided are:
# 1) Allows all UDP traffic on port 15000 for IPOP 
# 2) Allows all UDP traffic on port 53 for DNS
# 3) Allows ping traffic
# 4) Allows all TCP traffic on port 22 for SSH
# 5) Block all other outgoing traffic except the above

dir="/usr/local/ipop"
System=`$dir/scripts/Env.sh`

# Flush all existing rules 
iptables -F

if [[ $System = "linux" || $System = "xen0" ]]; then
  # Allow incoming and outgoing traffic on UDP port 15000 for IPOP
  iptables -A OUTPUT -p udp -o eth0 --sport 15000:15099 -j ACCEPT
  iptables -A INPUT -p udp -i eth0 --dport 15000:15099 -j ACCEPT

  # Allows incoming and outgoing traffic on UDP port 53 for DNS
  iptables -A OUTPUT -p udp -o eth0 --dport 53 -j ACCEPT
  iptables -A INPUT -p udp -i eth0 --sport 53 -j ACCEPT
  iptables -A OUTPUT -p tcp -o eth0 --dport 53 -j ACCEPT
  iptables -A INPUT -p tcp -i eth0 --sport 53 -j ACCEPT

  # Allows IPRouter DHCP traffic
  iptables -A OUTPUT -p tcp -o eth0 --dport 9202 -j ACCEPT
  iptables -A INPUT -p tcp -i eth0 --sport 9202 -j ACCEPT

  # Allows access to DHCP
  iptables -A OUTPUT -o eth0 -p udp --sport 68 --dport 67 -j ACCEPT
  iptables -A INPUT -i eth0 -p udp --sport 67 --dport 68 -j ACCEPT

  # Allows ping traffic
  iptables -A OUTPUT -p icmp -j ACCEPT
  iptables -A INPUT -p icmp -j ACCEPT

  # Block all outgoing trafiic except above
  iptables -A OUTPUT -o eth0 -j DROP
  iptables -A INPUT -i eth0 -j DROP
fi

if [[ $System = "linux" || $System = "xenU" ]]; then
  if [[ $System = "linux" ]]; then
    dev=tap0
  elif [[ $System = "xenU" ]]; then
    dev=eth0
  fi
  # Block SSH over IPOP
  iptables -A OUTPUT -p tcp -o $dev --dport 22 -j DROP
  iptables -A INPUT -p tcp -i $dev --sport 22 -j DROP
  iptables -A OUTPUT -p tcp -o $dev --sport 22 -j DROP
  iptables -A INPUT -p tcp -i $dev --dport 22 -j DROP
fi

if test -f /home/griduser/local_iprules; then
  /home/griduser/local_iprules
fi
