#!/bin/bash
# This script does the following:
# (a) Flushes the existing iptables rules and 
# (b) Defines the iptables rules for Grid-Appliance.
# (c) Displays the current iptable

# The rules and other functionalities provided are:
# 1) Allows all UDP traffic on port 15000 for IPOP 
# 2) Allows all UDP traffic on port 53 for DNS
# 3) Allows ping traffic
# 4) Allows all TCP traffic on port 22 for SSH
# 5) Block all other outgoing traffic except the above

dir="/usr/local/ipop"

# Flush all existing rules 
iptables -F

# Allows incoming and outgoing traffic on UDP port 53 for DNS
iptables -A OUTPUT -p udp -o eth0 --dport 53 -j ACCEPT
iptables -A INPUT -p udp -i eth0 --sport 53 -j ACCEPT
iptables -A OUTPUT -p tcp -o eth0 --dport 53 -j ACCEPT
iptables -A INPUT -p tcp -i eth0 --sport 53 -j ACCEPT

# Allows IPRouter DHCP traffic
#iptables -A OUTPUT -p tcp -o eth0 --dport 9203 -j ACCEPT
#iptables -A INPUT -p tcp -i eth0 --sport 9203 -j ACCEPT

# Allows access to DHCP
iptables -A OUTPUT -o eth0 -p udp --sport 68 --dport 67 -j ACCEPT
iptables -A INPUT -i eth0 -p udp --sport 67 --dport 68 -j ACCEPT

# Allows ping traffic
#iptables -A OUTPUT -p icmp -j ACCEPT
#iptables -A INPUT -p icmp -j ACCEPT

pid=`$dir/scripts/utils.sh get_pid IPRouter`
if [[ $pid = "" ]]; then
  iptables -F
  exit
fi

port=`$dir/scripts/utils.sh get_port $pid`
while [[ $port = '' ]]; do
  sleep 5
  echo "Waiting on IPOP"
  pid=`$dir/scripts/utils.sh get_pid IPRouter`
  if [[ $pid = "" ]]; then
    iptables -F
    exit
  fi
  port=`$dir/scripts/utils.sh get_port $pid`
done
iptables -I OUTPUT -p udp -o eth0 --sport $port -j ACCEPT
iptables -I INPUT -p udp -i eth0 --dport $port -j ACCEPT

# Block all outgoing trafiic except above
iptables -A OUTPUT -o eth0 -j DROP
iptables -A INPUT -i eth0 -j DROP

# Block SSH over IPOP
iptables -A OUTPUT -p tcp -o tap0 --dport 22 -j DROP
iptables -A INPUT -p tcp -i tap0 --sport 22 -j DROP
iptables -A OUTPUT -p tcp -o tap0 --sport 22 -j DROP
iptables -A INPUT -p tcp -i tap0 --dport 22 -j DROP

# Block nobody from sending over tap0
# iptables -A OUTPUT -m owner --uid-owner 65534 -j DROP


if test -f /home/griduser/local_iprules; then
  /home/griduser/local_iprules
fi
